import { SITE_URL } from "@/lib/blog-posts"

/**
 * Default next/image quality. Must be listed in `images.qualities` in
 * next.config.ts — the optimizer 400s on any value not declared there.
 */
export const DEFAULT_IMAGE_QUALITY = 75

/** Static fallback card, 1200x630, generated by scripts/generate-og-image.mjs. */
export const DEFAULT_OG_IMAGE = "/og-image.jpg"

/**
 * Width requested for social/JSON-LD images. Must be listed in
 * `images.deviceSizes` in next.config.ts, or the optimizer 400s and every
 * social preview on the site breaks at once.
 */
export const SOCIAL_IMAGE_WIDTH = 1200

export function isNextOptimizedImageSrc(src: string) {
  const trimmed = src.trim()
  if (!trimmed) return false
  if (trimmed.startsWith("/")) return true
  if (trimmed.includes("images.unsplash.com")) return true
  if (trimmed.includes(".supabase.co")) return true
  return false
}

/**
 * Absolute URL for an `og:image`, `twitter:image` or JSON-LD `image` field,
 * routed through the Next image optimizer where possible.
 *
 * Social and search crawlers do not read page HTML for these — they fetch the
 * URL in the metadata. Emitting a raw Supabase Storage URL meant Googlebot-Image
 * and facebookexternalhit pulled full-size originals on every crawl and every
 * share, which was the last significant source of Storage egress after the
 * on-page images were fixed.
 *
 * Format negotiation makes this safe for social crawlers. Next only honours a
 * negotiated type when the raw Accept header literally contains it
 * (`accept.includes(mimeType)` in next/dist/server/image-optimizer.js), so a
 * crawler sending `Accept: * / *` falls through to the original upstream format:
 * browsers get WebP, Facebook and Twitter get a resized JPEG.
 */
export function socialImageUrl(src: string | null | undefined): string {
  const trimmed = src?.trim()
  if (!trimmed) return `${SITE_URL}${DEFAULT_OG_IMAGE}`

  // Local assets are already sized for social (1200x630) and cost nothing to
  // serve — routing them through the optimizer would burn a transformation.
  if (trimmed.startsWith("/")) return `${SITE_URL}${trimmed}`

  // Only hosts allowed by `images.remotePatterns` can go through the optimizer;
  // anything else would return 400 and break the preview outright rather than
  // degrade it, so pass unknown hosts through untouched.
  if (!isNextOptimizedImageSrc(trimmed)) return trimmed

  const params = new URLSearchParams({
    url: trimmed,
    w: String(SOCIAL_IMAGE_WIDTH),
    q: String(DEFAULT_IMAGE_QUALITY),
  })
  return `${SITE_URL}/_next/image?${params.toString()}`
}

export function formatImageBytes(bytes: number) {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(bytes < 10_240 ? 1 : 0)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}
